services:
  ollama:
    image: ollama/ollama
    container_name: ollama
    environment:
      - OLLAMA_HOST=0.0.0.0:11434
      - OLLAMA_MAX_LOADED_MODELS=2
      - OLLAMA_KEEP_ALIVE=-1
    ports:
      - "11434:11434"
    volumes:
      - ./.ollama:/root/.ollama

volumes:
  ollama:
